import { useState } from "react";
import { Link } from "wouter";
import { Activity, ArrowLeft, Eye, FileText, LockKeyhole, LogOut, ShieldCheck, Users } from "lucide-react";
import { trpc } from "@/lib/trpc";

export default function Admin() {
  const [password, setPassword] = useState("");
  const [authenticated, setAuthenticated] = useState(false);
  const adminLogin = trpc.admin.login.useMutation({ onSuccess: () => { setAuthenticated(true); setPassword(""); } });
  const adminLogout = trpc.admin.logout.useMutation({ onSuccess: () => setAuthenticated(false) });
  const requests = trpc.admin.requests.useQuery(undefined, { enabled: authenticated, retry: false });
  const visitors = trpc.admin.visitors.useQuery(undefined, { enabled: authenticated, retry: false });

  function signIn(event: React.FormEvent) { event.preventDefault(); if (password) adminLogin.mutate({ password }); }
  const requestCount = requests.data ? Object.keys(requests.data).length : 0;
  const visitorCount = visitors.data ? Object.keys(visitors.data).length : 0;

  if (!authenticated) return <div className="admin-gate"><div className="admin-gate-card"><Link href="/" className="admin-back"><ArrowLeft size={16}/> العودة للموقع</Link><div className="admin-lock"><LockKeyhole size={28}/></div><span className="section-kicker">NBE / PRIVATE AREA</span><h1>لوحة الإدارة</h1><p>هذه المساحة محمية ومخصصة للجهة المالكة للموقع.</p><form onSubmit={signIn}><label>كلمة المرور<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="••••••••" autoComplete="current-password"/></label>{adminLogin.error && <p className="error-text">كلمة المرور غير صحيحة أو تعذر الاتصال بالخادم.</p>}<button className="primary-button" type="submit" disabled={adminLogin.isPending}>{adminLogin.isPending ? "جارٍ التحقق..." : "دخول"} <ArrowLeft size={17}/></button></form><div className="admin-security-note"><ShieldCheck size={17}/> التحقق يتم على الخادم ولا تُحفظ كلمة المرور في المتصفح.</div></div></div>;

  return <div className="admin-shell rtl" dir="rtl"><aside className="admin-sidebar"><Link href="/" className="admin-brand">NBE <span>WATCHES</span></Link><nav><a className="active" href="#overview"><Activity size={18}/> نظرة عامة</a><a href="#requests"><FileText size={18}/> الطلبات</a><a href="#visitors"><Eye size={18}/> الزيارات النشطة</a></nav><button className="admin-logout" onClick={() => adminLogout.mutate()}><LogOut size={17}/> تسجيل الخروج</button></aside><main className="admin-main"><div className="admin-topbar"><div><span className="section-kicker">NBE / ADMIN</span><h1>مرحبًا بك في لوحة الإدارة</h1></div><div className="admin-status"><span className="status-dot"/> النظام يعمل</div></div><section className="stat-grid"><article className="stat-card"><span><Users size={20}/></span><p>الزوار النشطون</p><strong>{visitors.isLoading ? "…" : visitorCount}</strong><small>آخر نبضات مسجلة في Firebase</small></article><article className="stat-card"><span><FileText size={20}/></span><p>الطلبات الجديدة</p><strong>{requests.isLoading ? "…" : requestCount}</strong><small>طلبات محفوظة بأمان</small></article><article className="stat-card"><span><Eye size={20}/></span><p>حالة الاتصال</p><strong>{requests.error || visitors.error ? "!" : "OK"}</strong><small>{requests.error || visitors.error ? "تحقق من صلاحية Firebase" : "الخادم متصل"}</small></article></section><section className="admin-panel" id="requests"><div className="panel-heading"><div><span className="section-kicker">LIVE FEED</span><h2>الطلبات والزيارات</h2></div><span className="panel-badge">محمية</span></div><div className="admin-data-grid"><div><h3>آخر الطلبات</h3>{requestCount === 0 ? <div className="empty-panel"><FileText size={28}/><p>لا توجد طلبات جديدة.</p></div> : <div className="data-list">{Object.entries(requests.data ?? {}).slice(-8).reverse().map(([key, item]: [string, any]) => <div className="data-row" key={key}><strong>{item.name ?? "—"}</strong><span>{item.email ?? "—"}</span><small>{item.createdAt ? new Date(item.createdAt).toLocaleString("ar-EG") : "—"}</small></div>)}</div>}</div><div id="visitors"><h3>الزيارات النشطة</h3>{visitorCount === 0 ? <div className="empty-panel"><Activity size={28}/><p>لا توجد زيارات مسجلة حاليًا.</p></div> : <div className="data-list">{Object.entries(visitors.data ?? {}).slice(-8).reverse().map(([key, item]: [string, any]) => <div className="data-row" key={key}><strong>{item.path ?? "/"}</strong><span>{item.language === "en" ? "English" : "العربية"}</span><small>{item.lastSeenAt ? new Date(item.lastSeenAt).toLocaleString("ar-EG") : "—"}</small></div>)}</div>}</div></div></section></main></div>;
}
